import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Script from "next/script";
import Calcumate from "./Calcumate/Calcumate";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Step to build your own calcumate calculator
        </h1>
        <ul>
          <li>Go to <a href="https://www.calcumate.co" target="_blank"> calcumate.co</a></li>
          <li>Sign up for a free Account</li>
          <li>Use ngrok to expose a local development server to the Internet.</li>
          <li>Create a calculator at last step you would get your own calculator to add to Calcumate.tsx</li>
        </ul>
        <h1 className={styles.title}>Should show a view below.</h1>
        <div className={styles.grid}>
          <Calcumate />
        </div>
        <Script
          src="https://calcumate-calculator-new-production.s3-ap-southeast-2.amazonaws.com/static/js/main.js"
          strategy="afterInteractive"
          defer
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
